[package]
name = "bulk-ether"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0"}
tokio = { version = "1", features = ["full"] }
rpassword = "7.0"
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }